services:
  # this spawns the local github page
  website:
    image: website
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    environment:
      - DISPLAY=$DISPLAY
    container_name: website
    tty: true  # docker run -t
    stdin_open: true  # docker run -i
    ports:
      - "4000:4000"
    # user: 1000:1000
    working_dir: /website
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - type: bind
        source: ../
        target: /website
    # command: "/bin/bash"
    command: "bundle exec jekyll serve"
