name: Update Resume

on:
  push:
    branches: [ "fix-resume" ]
  pull_request:
    branches: [ "fix-resume" ]
  # schedule:
  #  - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      #with: 
      #repository: cschindlbeck/cv
      #ref: refs/heads/main
    - name: Build Resume
      run: |
        # Cloning via PAT
        git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/cschindlbeck/cv.git
        cd cv
        ./latexdockercmd.sh pdflatex resume_cschindlbeck.tex
        cd ..
        cp cv/resume_cschindlbeck.pdf assets/docs/resume_cschindlbeck.pdf
        rm -rf cv
    - name: Push code
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # Force add since README is on gitignore
        git add -f assets/docs/resume_cschindlbeck.pdf
        git stash
        git pull origin ${GITHUB_REF##*/} --rebase
        # Prevent empty add to result in error
        git diff-index --quiet HEAD || git commit -m "Updated Resume"
        git push
